[fish-extract]
src.git = "https://github.com/oh-my-fish/plugin-extract"
fetch.github = "oh-my-fish/plugin-extract"

[fish-autols]
src.git = "https://github.com/rstacruz/fish-autols"
fetch.github = "rstacruz/fish-autols"

[fish-balias]
src.git = "https://github.com/oh-my-fish/plugin-balias"
fetch.github = "oh-my-fish/plugin-balias"

[fish-emptyls]
src.git = "https://github.com/Omochice/emptyls-fish"
fetch.github = "Omochice/emptyls-fish"

[fish-fzf-emoji]
src.git = "https://github.com/Omochice/fzf-emoji.fish"
fetch.github = "Omochice/fzf-emoji.fish"

[fish-lazyasdf]
src.git = "https://github.com/Omochice/lazyasdf.fish"
fetch.github = "Omochice/lazyasdf.fish"

[fish-direnv]
src.git = "https://github.com/usami-k/fish-direnv"
fetch.github = "usami-k/fish-direnv"

[fish-catputtin]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

[yazi-theme-catppuccin]
src.git = "https://github.com/catppuccin/yazi"
fetch.github = "catppuccin/yazi"

[bat-theme-catppuccin]
src.git = "https://github.com/catppuccin/bat"
fetch.github = "catppuccin/bat"

[zathura-catputtin]
src.git = "https://github.com/catppuccin/zathura"
fetch.github = "catppuccin/zathura"

[gh-q]
src.git = "https://github.com/kawarimidoll/gh-q"
fetch.github = "kawarimidoll/gh-q"

[gh-fzgist]
src.git = "https://github.com/Omochice/gh-fzgist"
fetch.github = "Omochice/gh-fzgist"

[gh-userfetch]
src.git = "https://github.com/sheepla/gh-userfetch"
fetch.github = "sheepla/gh-userfetch"

[claude-skill-ast-grep]
src.git = "https://github.com/ast-grep/claude-skill"
fetch.github = "ast-grep/claude-skill"

[neovim]
src.git = "https://github.com/neovim/neovim"
fetch.github = "neovim/neovim"

[anthropic-skills]
src.git = "https://github.com/anthropics/skills"
fetch.github = "anthropics/skills"
